addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.5.6")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.11.4")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "2.4.2")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.11.0")
